title: PL&C
remote_theme: pmarsceill/just-the-docs
#color_scheme: foo
compress_html:
  ignore:
    envs: all
  blanklines: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
aux_links:
  "Unit Webpage":
    - "https://www.ole.bris.ac.uk/auth-saml/saml/login?apId=_183_1&redirectUrl=https%3A%2F%2Fwww.ole.bris.ac.uk%2Fultra%2Fcourses%2F_260086_1%2Fcl%2Foutline"
domain: uob-coms20007.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://uob-coms20007.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /reference/      # place folder name if the site is served in a subfolder
